### PR TITLE
Use own forks

### PR DESCRIPTION
**Pull request by DeviaVir**
For added security and sanity, use our own forks so we fully control the deploy and maintain pipeline.

Reviewers: @aheckmann-pebble @jlai

### CODE REVIEW

**Comment by thepwagner** [comment]
+1

Alternative: verify SHA256 of the downloaded artifacts? RSA signature would be better but upstream doesn't sign :(
All the paranoia with none of the maintenance overhead.

**Comment by DeviaVir** [comment]
Do we want to use forks on docker hub as well? For: https://github.com/pebble/nginx-proxy/blob/master/Makefile#L5

**Comment by aheckmann-pebble** [comment]
I'm +0. Would love to remove forego at some point .

**Comment by jlai** [comment]
+1.

I think that Makefile is only used for ci

**Pull request merged**
